// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxiTz5FoPtoofATXrpbcWhWpYMP_5AFsc',
    appId: '1:45133562959:web:469584549eb4ca1fedd63a',
    messagingSenderId: '45133562959',
    projectId: 'autopetutt',
    authDomain: 'autopetutt.firebaseapp.com',
    databaseURL: 'https://autopetutt-default-rtdb.firebaseio.com',
    storageBucket: 'autopetutt.firebasestorage.app',
    measurementId: 'G-Q2EPZL58JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyu8DZ1d7Kw_8Mf5PVNt5KkO9vIx8xsbk',
    appId: '1:45133562959:android:c15559e9f7669f46edd63a',
    messagingSenderId: '45133562959',
    projectId: 'autopetutt',
    databaseURL: 'https://autopetutt-default-rtdb.firebaseio.com',
    storageBucket: 'autopetutt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnKhVZVmzBdFnbV8mqIMsb4F-JbvqO90',
    appId: '1:45133562959:ios:9934fd532bfb6d96edd63a',
    messagingSenderId: '45133562959',
    projectId: 'autopetutt',
    databaseURL: 'https://autopetutt-default-rtdb.firebaseio.com',
    storageBucket: 'autopetutt.firebasestorage.app',
    iosBundleId: 'com.example.integradoraAppmovil3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqnKhVZVmzBdFnbV8mqIMsb4F-JbvqO90',
    appId: '1:45133562959:ios:9934fd532bfb6d96edd63a',
    messagingSenderId: '45133562959',
    projectId: 'autopetutt',
    databaseURL: 'https://autopetutt-default-rtdb.firebaseio.com',
    storageBucket: 'autopetutt.firebasestorage.app',
    iosBundleId: 'com.example.integradoraAppmovil3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxiTz5FoPtoofATXrpbcWhWpYMP_5AFsc',
    appId: '1:45133562959:web:a64c72aa2acbb423edd63a',
    messagingSenderId: '45133562959',
    projectId: 'autopetutt',
    authDomain: 'autopetutt.firebaseapp.com',
    databaseURL: 'https://autopetutt-default-rtdb.firebaseio.com',
    storageBucket: 'autopetutt.firebasestorage.app',
    measurementId: 'G-9F1SGN8FL4',
  );

}