// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjyfjp4WcY2BlzWnjaaeSX-di2c1gWs4',
    appId: '1:91405691226:web:447bd4452de55aee756b63',
    messagingSenderId: '91405691226',
    projectId: 'integradoratest',
    authDomain: 'integradoratest.firebaseapp.com',
    storageBucket: 'integradoratest.firebasestorage.app',
    measurementId: 'G-TEBVW0EZ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9fmcosKor9MVBC7z6Z01khlCzXq4P7rw',
    appId: '1:91405691226:android:ec80ea4dcc3ea5d8756b63',
    messagingSenderId: '91405691226',
    projectId: 'integradoratest',
    storageBucket: 'integradoratest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqT_8r7KsETi_MVjYvDsw6jYyzhWMtUQg',
    appId: '1:91405691226:ios:3dd53446bd9fdfec756b63',
    messagingSenderId: '91405691226',
    projectId: 'integradoratest',
    storageBucket: 'integradoratest.firebasestorage.app',
    iosBundleId: 'com.example.autopetUtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqT_8r7KsETi_MVjYvDsw6jYyzhWMtUQg',
    appId: '1:91405691226:ios:3dd53446bd9fdfec756b63',
    messagingSenderId: '91405691226',
    projectId: 'integradoratest',
    storageBucket: 'integradoratest.firebasestorage.app',
    iosBundleId: 'com.example.autopetUtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwjyfjp4WcY2BlzWnjaaeSX-di2c1gWs4',
    appId: '1:91405691226:web:9a3929d9c8d5143b756b63',
    messagingSenderId: '91405691226',
    projectId: 'integradoratest',
    authDomain: 'integradoratest.firebaseapp.com',
    storageBucket: 'integradoratest.firebasestorage.app',
    measurementId: 'G-KVY7QPY4SJ',
  );
}
